#### Create An object
- L = np.array([[1,2,1],[3,4,-1]])

#### Get the Shape
- L.shape

#### Return Indices of Maximum Elements
- np.argmax(L)

#### Return the indices whose values are -1
- np.where(L == -1)

#### Return the minimum of the matrix
- L.min()

#### Get all values at diagonal line
- L.diagonal()

#### Add (with matrix M)
- L = L + M

#### Delete the first row
- L = L[1:]

#### Stack
- np.vstack((L, newrow))

#### Multiplication (with matrix M)
- L = np.dot(L, M)

In [2]:
import numpy as np

In [14]:
L = np.array([[-1,2, 7], [3, 5, -1]])
M = np.array([1,-4,0,-1,1,1]).reshape(2,3)

In [15]:
L.shape

(2, 3)

In [16]:
np.argmax(L)

2

In [17]:
np.where(L == -1)

(array([0, 1]), array([0, 2]))

In [18]:
L.min()

-1

In [19]:
L.diagonal()

array([-1,  5])

In [20]:
L + M

array([[ 0, -2,  7],
       [ 2,  6,  0]])

In [21]:
L[1:]

array([[ 3,  5, -1]])

In [24]:
np.vstack((L, [3,3,3]))

array([[-1,  2,  7],
       [ 3,  5, -1],
       [ 3,  3,  3]])

In [25]:
M = M.reshape(3,2)
np.dot(L, M)

array([[  6,   9],
       [  2, -18]])