## Set Up Environment

In [44]:
import numpy as np
import json
import sys

In [57]:
input_path = 'summary2.json'
output_path = 'my_answer2.json'
m = 0.15
N = 50

## Load File

In [58]:
#read the file
link = []
with open(input_path,"r") as f:
    link=json.load(f)

## Matrix Preparation

In [59]:
#initialize original transition matrix
original_transition = np.zeros((len(link),len(link)))
for i in range(len(link)):
    for o in link[i]:
        original_transition[i][o] = 1

In [60]:
#normalize original transition matrix, avoid devide by 0.
totallink = np.sum(original_transition,axis=0)
for i in range(len(link)):
    if(totallink[i] == 0):
        totallink[i] = 1
original_transition = original_transition / totallink

print("Original transition matrix", original_transition)

initial_vector = np.ones(len(link))/len(link)

Original transition matrix [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Pagerank Algorithm
- M = (1-m)A + mS

A is original transition matrix, 
S is stochastic matrix

In [61]:
for i in range(len(link)):
    original_transition[i] = (1-m)*original_transition[i] + m*initial_vector

In [62]:
updated_vector = initial_vector
for j in range(N):
    updated_vector = original_transition @ updated_vector

In [63]:
ordering_of_websites = np.argsort(-1 * updated_vector)
print("Your current answer",ordering_of_websites)

#turn your answer from a numpy array to list and output it as a json file
ordering_of_websites = ordering_of_websites.tolist()
with open(output_path,"w") as f:
    json.dump(ordering_of_websites,f)

Your current answer [  4   6 223 229   2  35  54 242 138 246  37 196 116 274 114 155 111 131
 192 257 121 127 276 184 102 103 285 106  67  11 253 185 202  31  16 180
 156 254  58 267 256 126 273 233 264  15 135  40 118  90 266  68  44 281
 119 226 165 212 177  65 215 207 252  24 133 241 161 203   1 188 130  41
 143  42 277  53 249 173  55 100 219 214 136  83 268 164  43 149  97 144
 157  10 209 224 230 297  93  81 247 280 158  85  12  56 178 213  52  79
  71 234 112 159   3 270 198 295 269 206 186 263 139  19  63 191 236  86
 101 117 265 288  21 145  89 166  61  70  29 134 124 104 172 235 193 194
  13  48 171 251  20 299 201  17 227  28  96  39  22 279 108  36 239  23
  50 296 179 200 125 170 154 221 248  47 147 232  66 250 141 195 128  33
 293  76 260 140 283 243  18 162 182 217 259 210 284 148 160 129 294 225
 222   8 123   5 228  57  95  82  25  84 150 291 115 211  92 282  30 287
 175  88 218  80  87  14  49  62  99 109 122 204  26 278  98 153 113 286
  74   0 237 290 169 262 208 27